### ISSUE TITLE
CSS浮动与清除浮动

### ISSUE THREAD

**Issue by tanxd2002** [tanxd2002/blog#2]
通常的块元素布局，是自上而下的，每个div占据一行，我们称之为普通流（normal flow）。但往往在页面设计上需要并排显示多个div，这时候我们需要用到浮动（float）。

元素设置为float后，不属于包含框的普通流，也不影响包含框内的块元素，但会影响内联元素的排列。同时，由于脱离普通流的关系，如果包含框内没有其他普通流元素，高度就会为0（高度塌陷）。
### 如何清除浮动（闭合浮动）？
1. 触发父元素BFC
   
   例如：设置overflow,float,display等等， 这些改动会导致一些问题，如设置overflow:hidden会导致内容过多时，溢出部分无法显示；设置float会影响父元素的布局；设置display:table会改变盒属性，导致一系列问题。因此该方法不好。
2. clear:both
   
   在浮动元素后面，增加一个空的元素，并设置clear:both。不过这样会导致代码中大量出现这样的空元素，代码不美观，不利于维护。

---
### 比较优雅的实现方法，还是用方法2，但使用伪元素:after，在浮动层最后插入一个带clear:both的空元素。

``` css
 .clearfix:after {content:"\200B"; display:block; height:0; clear:both; }
```

如果要考虑IE6的话，可以加上zoom:1，来触发hasLayout

``` css
.clearfix { *zoom:1; }
```
